AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Configure the AWS Landing Zone Security Roles to enable access to target
  accounts and GuardDuty Master.
Parameters:
  AdminRoleName:
    Type: String
    Description: Role name for administrator access.
    Default: AWSLandingZoneSecurityAdministratorRole
  ReadOnlyRoleName:
    Type: String
    Description: Role name for read-only access.
    Default: AWSLandingZoneSecurityReadOnlyRole
Resources:
  AdministrationRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Ref AdminRoleName
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: AssumeRole-AWSLandingZoneSecurityAdministratorRole
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'sts:AssumeRole'
                Resource:
                  - 'arn:aws:iam::*:role/AWSLandingZoneAdminExecutionRole'
  ReadOnlyRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Ref ReadOnlyRoleName
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: AssumeRole-AWSLandingZoneSecurityReadOnlyRole
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'sts:AssumeRole'
                Resource:
                  - 'arn:aws:iam::*:role/AWSLandingZoneReadOnlyExecutionRole'
  MasterDetector:
    Type: 'AWS::GuardDuty::Detector'
    Properties:
      Enable: true
  GuardDutyFindingEventRule:
    Type: 'AWS::Events::Rule'
    Properties:
      Name: GuardDuty-Finding
      Description: Landing Zone rule to send notification on GuardDuty findings.
      EventPattern:
        source:
          - aws.guardduty
        detail-type:
          - GuardDuty Finding
      State: ENABLED
Outputs:
  CrossAccountAdminRole:
    Description: AWS Landing Zone Security Administrator Role
    Value: !GetAtt AdministrationRole.Arn
    Export:
      Name: AdminRoleArn
  CrossAccountReadOnlyRole:
    Description: AWS Landing Zone Security ReadOnly Role
    Value: !GetAtt ReadOnlyRole.Arn
    Export:
      Name: ReadOnlyRoleArn
  MasterDetectorId:
    Description: GuardDuty DetectorId for this region
    Value: !Ref MasterDetector