AWSTemplateFormatVersion: 2010-09-09
Description: Account Builder Template for log-archive.
Parameters:
  accountemail:
    Description: Account Email address
    Type: String
    AllowedPattern: .+
    ConstraintDescription: Must provide a valid email address
  accountname:
    Description: Name of the new AWS Account Name
    Type: String
    AllowedPattern: .+
    ConstraintDescription: Provide the account name
  s3BucketName:
    Type: String
    Description: Bucket Name for cloudtrail
    Default: aws-landing-zone-logs-IB
  s3loggingBucketName:
    Type: String
    Description: Logging Bucket name
    Default: aws-landing-zone-access-IB
  organizationunitname:
    Description: Name of the organization unit to which the account should be moved to.
    Type: String
    Default: None
    AllowedPattern: .+
  newrole:
    Description: >-
      Role that needs to be created in the newly built account. Use
      OrganizationAccountAccessRole for assuming roles into the new account,in
      case this role creation fails.
    Default: $client-assumerole
    Type: String
    AllowedPattern: .+
  newrolepolicy:
    Description: >-
      Provide the policy to be attached to the above newrole. Json is only the
      valid format.
    Default: >-
      {"Version":"2012-10-17","Statement":{"Effect":"Allow","Action":"*","Resource":"*"}}
    Type: String
    AllowedPattern: .+
  stackname:
    Description: Name given to the stack deployed in the created account.
    Type: String
    AllowedPattern: .+
    ConstraintDescription: >-
      Must contain only letters, numbers, dashes and start with an alpha
      character
  stackregion:
    Description: Region for deploying the baseline template in the created account
    Default: ap-southeast-1
    Type: String
    AllowedPattern: .+
    AllowedValues:
      - us-east-2
      - us-east-1
      - us-west-1
      - us-west-2
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-south-1
      - ap-southeast-1
      - ap-southeast-2
      - ca-central-1
      - cn-north-1
      - cn-northwest-1
      - eu-central-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - sa-east-1
    ConstraintDescription: Must be a valid AWS region
  sourcebucket:
    Description: Bucket holding the baseline template file
    Type: String
    AllowedPattern: .+
  baselinetemplate:
    Description: Baseline template to be deployed in the created account.
    Type: String
    Default: baseline-log.yaml
    AllowedPattern: .+
  AZ1Name:
    Description: Availability Zone 1 Name in Region
    Type: String
    AllowedPattern: .+
    AllowedValues:
      - ap-south-1a
      - ap-south-1b
      - eu-west-3a
      - eu-west-3b
      - eu-west-3c
      - eu-west-2a
      - eu-west-2b
      - eu-west-2c
      - eu-west-1a
      - eu-west-1b
      - eu-west-1c
      - ap-northeast-3a
      - ap-northeast-2a
      - ap-northeast-2c
      - ap-northeast-1a
      - ap-northeast-1c
      - ap-northeast-1d
      - sa-east-1a
      - sa-east-1c
      - ca-central-1a
      - ca-central-1b
      - ap-southeast-1a
      - ap-southeast-1b
      - ap-southeast-1c
      - ap-southeast-2a
      - ap-southeast-2b
      - ap-southeast-2c
      - eu-central-1a
      - eu-central-1b
      - eu-central-1c
      - us-east-1a
      - us-east-1b
      - us-east-1c
      - us-east-1d
      - us-east-1e
      - us-east-1f
      - us-east-2a
      - us-east-2b
      - us-east-2c
      - us-west-1b
      - us-west-1c
      - us-west-2a
      - us-west-2b
      - us-west-2c
  AZ2Name:
    Description: Availability Zone 2 Name in Region
    Type: String
    AllowedPattern: .+
    AllowedValues:
      - ap-south-1a
      - ap-south-1b
      - eu-west-3a
      - eu-west-3b
      - eu-west-3c
      - eu-west-2a
      - eu-west-2b
      - eu-west-2c
      - eu-west-1a
      - eu-west-1b
      - eu-west-1c
      - ap-northeast-3a
      - ap-northeast-2a
      - ap-northeast-2c
      - ap-northeast-1a
      - ap-northeast-1c
      - ap-northeast-1d
      - sa-east-1a
      - sa-east-1c
      - ca-central-1a
      - ca-central-1b
      - ap-southeast-1a
      - ap-southeast-1b
      - ap-southeast-1c
      - ap-southeast-2a
      - ap-southeast-2b
      - ap-southeast-2c
      - eu-central-1a
      - eu-central-1b
      - eu-central-1c
      - us-east-1a
      - us-east-1b
      - us-east-1c
      - us-east-1d
      - us-east-1e
      - us-east-1f
      - us-east-2a
      - us-east-2b
      - us-east-2c
      - us-west-1b
      - us-west-1c
      - us-west-2a
      - us-west-2b
      - us-west-2c
Resources:
  bucketParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: s3bucketname
      Type: String
      Value: !Ref s3BucketName
      Description: s3 bucket Name for cloudtrail logs.
  loggingbucketParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: s3loggingbucketname
      Type: String
      Value: !Ref s3loggingBucketName
      Description: s3 bucket Name for cloudwatch log.
  AccountBuilderLambda:
    Type: 'AWS::Lambda::Function'
    Properties:
      Handler: AccountCreationLambda.main
      Runtime: python3.6
      Role: !GetAtt LambdaExecuteRole.Arn
      Timeout: 600
      TracingConfig:
        Mode: Active
      Code:
        S3Bucket: !Ref sourcebucket
        S3Key: AccountCreationLambda-log.zip
      Environment:
        Variables:
          accountemail: !Ref accountemail
          accountname: !Ref accountname
          newrolepolicy: !Ref newrolepolicy
          newrole: !Ref newrole
          organizationunitname: !Ref organizationunitname
          stackname: !Ref stackname
          stackregion: !Ref stackregion
          sourcebucket: !Ref sourcebucket
          baselinetemplate: !Ref baselinetemplate
          AZ1Name: !Ref AZ1Name
          AZ2Name: !Ref AZ2Name
          s3BucketName: !Ref s3BucketName
          s3loggingBucketName: !Ref s3loggingBucketName
  LambdaExecuteRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          Effect: Allow
          Principal:
            Service:
              - lambda.amazonaws.com
          Action:
            - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: LambdaAccessRole
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              Effect: Allow
              Action: '*'
              Resource: '*'
  TriggerLambda:
    Type: 'Custom::TriggerLambda'
    DeletionPolicy: Retain
    DependsOn:
      - AccountBuilderLambda
      - LambdaExecuteRole
    Properties:
      ServiceToken: !GetAtt AccountBuilderLambda.Arn
Outputs:
  Message:
    Description: Execution Status
    Value: !GetAtt TriggerLambda.Message
  AccountID:
    Description: ID of the new account
    Value: !GetAtt TriggerLambda.AccountID
  S3BucketName:
    Description: Cloudtrail Bucket Name
    Value: !Ref s3BucketName
  loggingBucketName:
    Description: Cloudtrail logging Bucket Name
    Value: !Ref s3loggingBucketName
